// Shared paper-title resolution for the Live globe + breakdown drawer.
//
// The client islands (LiveGlobe, BreakdownDrawer) can't read astro:content at
// runtime, so they resolve a paper's display title from this build-time map
// (generated by scripts/gen-paper-titles.mjs from the .mdx frontmatter).
//
// Resolution order:
//   1. curated .mdx title for the slug   (authoritative, properly capitalized)
//   2. the title stored on the event row  (legacy / external events)
//   3. a sentence-cased version of the slug (last-resort fallback — never the
//      raw lowercase "coworkers solidarity deviant behavior")
import paperTitles from '../data/paper-titles.json';

const CURATED = paperTitles as Record<string, string>;

/** "coworkers-solidarity-deviant-behavior" -> "Coworkers solidarity deviant behavior" */
export function sentenceCaseSlug(slug: string): string {
  const s = slug.replace(/-/g, ' ').trim();
  return s ? s.charAt(0).toUpperCase() + s.slice(1) : s;
}

export function resolvePaperTitle(
  slug: string | null | undefined,
  eventTitle?: string | null,
): string | null {
  if (slug && CURATED[slug]) return CURATED[slug];
  if (eventTitle) return eventTitle;
  if (slug) return sentenceCaseSlug(slug);
  return null;
}
